server:
  port: 8081

spring:
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/air_s_2
    username: postgres
    password: 123